[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cnis-parse-app"
version = "0.1.2"
description = "SAAS para extrair dados de documentos CNIS."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "pdfplumber",
    "fastapi",
    "jinja2",
    "supabase",
    "uvicorn",
    "python-dotenv",
    "python-multipart"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]

[project.optional-dependencies]
dev = ["ruff", "pytest", "pytest-asyncio", "pre-commit"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM"]  # erros, imports, upgrades, bugbear, simplify

[tool.pytest.ini_options]
testpaths = ["tests"]
